name: GENERATE IMAGE

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_DEFAULT }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEFAULT }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_DEFAULT }}
        run: |
          gcloud auth configure-docker \us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT/live-interactive-games/backend:latest .
          docker push us-central1-docker.pkg.dev/$GCP_PROJECT/live-interactive-games/backend:latest
